version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "latency-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kjqzy0abzdhz"
s3_prefix = "latency-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ARecord=\"10.241.44.232\""
image_repositories = []
