AWSTemplateFormatVersion: 2010-09-09

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  Route53DomainName:
    Type: String
  ApiIrelandHostedZoneId:
    Type: String
  ApiIrelandDomainName:
    Type: String
  ApiIrelandEndpoint:
    Type: String

Resources:
##########################################################################
#  Health Check                                                          #
##########################################################################
  HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        EnableSNI: true
        FullyQualifiedDomainName: !Sub ${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com
        Type: HTTPS
        FailureThreshold: 5 ## Default is 3
        MeasureLatency: true ## Cannot be changed after creation
        ResourcePath: /Prod
##########################################################################
#  Hosted Zone                                                              #
##########################################################################
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: 'My hosted zone for nsncareer.com'
      Name: 'www.nsncareer.com'
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: 'nsncareer_logs'
      VPCs:
        - VPC: 'vpc-063f8b21a548c037c'

##########################################################################
#  Route53                                                               #
##########################################################################
  DNSARecordGroup:    
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets: 
        - Name: 'xxxx.nsncareer.com'
          Type: CNAME
          TTL: '900'
          SetIdentifier: Frontend One 'Germany'
          Weight: '140'
          ResourceRecords:
            - example-ec2.amazonaws.com
        - Name: 'xxxx.nsncareer.com'
          Type: CNAME
          TTL: '900'
          SetIdentifier: Frontend Two
          Weight: '60'
          ResourceRecords:
            - example-ec2-larger.amazonaws.com
