version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weighted-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kjqzy0abzdhz"
s3_prefix = "weighted-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ARecordOne=\"54.251.92.166\" ARecordTwo=\"54.172.8.44\""
image_repositories = []
