AWSTemplateFormatVersion: 2010-09-09

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  ARecordOne:
    Type: String
  ARecordTwo:
    Type: String

Resources:
##########################################################################
#  Route53 Load balancer                                                 #
##########################################################################
  myELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Subnets:
        - subnet-002fb04124cdabd8d
        - subnet-05fbe185988170f50
##########################################################################
#  Health Check                                                          #
##########################################################################
  HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        EnableSNI: true
        FullyQualifiedDomainName: www.nsncareer.com
        Type: HTTPS
        FailureThreshold: 5 ## Default is 3
        MeasureLatency: true ## Cannot be changed after creation
        ResourcePath: /
##########################################################################
#  Hosted Zone                                                              #
##########################################################################
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: 'My hosted zone for weighted routing policy'
      Name: nsncareer.com


##########################################################################
#  Route53                                                               #
##########################################################################
  DNSARecordGroup:    
    Type: AWS::Route53::RecordSetGroup
    DependsOn: myELB
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets: 
        - Name: myELB.nsncareer.com
          Type: A
          TTL: '900'
          SetIdentifier: Frontend One 'Germany'
          Weight: '90'
          ResourceRecords:
            - !Ref ARecordOne
        - Name: myELB.nsncareer.com
          Type: A
          TTL: '900'
          SetIdentifier: Frontend Two
          Weight: '10'
          ResourceRecords:
            - !Ref ARecordTwo
