AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Failover example
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: python3.9
  Api:
    TracingEnabled: True


Parameters:
  Priority:
    Type: String
    Description: PRIMARY or SECONDARY
    AllowedValues: ["PRIMARY", "SECONDARY"]

Resources:
  CustomDomain: # Creates the domain name
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: 'nsncareer.com'
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: '*.nsncareer.com'
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: 'My hosted zone for nsncareer.com'
      Name: 'www.nsncareer.com'
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: 'nsncareer_logs'
      VPCs:
        - VPC : 'vpc-063f8b21a548c037c'

  RestApiMapping: #Create a maooing to a REST API
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref RestApiGateway
      DomainName: 'nsncareer.com'
      Stage: Prod

  RestApiGateway: # Creates a REST API endpoint
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Architectures:
        - arm64
      Events:
        Fetch:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /
            Method: get

  HealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        EnableSNI: true
        FullyQualifiedDomainName: !Sub ${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com
        Type: HTTPS
        FailureThreshold: 5 ## Default is 3
        MeasureLatency: true ## Cannot be changed after creation
        ResourcePath: /Prod

  FailoverRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Failover: !Ref Priority
      Name: 'nsncareer.com'
      HostedZoneId: !Ref HostedZone
      SetIdentifier: !Sub ${AWS::Region}-failover
      HealthCheckId: !Ref HealthCheck
      TTL: 60
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId
      Type: A

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"